pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
    post {
        always {
            echo 'This will always run!'
            sh 'cp products/074.primetools.docs.pwa/index.html /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/docs/index.html'
            sh 'cp products/074.primetools.docs.pwa/manifest.webmanifest /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/docs/manifest.webmanifest'
            sh 'cp products/074.primetools.docs.pwa/images/ /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/docs/'
            sh 'cp products/074.primetools.docs.pwa/bangsplat.jpg /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/docs/bangsplat.jpg'
            sh 'cp products/074.primetools.docs.pwa/prime-tools-docs-sw.js /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/docs/prime-tools-docs-sw.js'
        }
        success {
            echo 'This will run only if successful.'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
