pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building'
                sh '. products/024.primetools.web.api/venv/bin/activate'
                sh 'pip3 install -r /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
                sh 'pytest /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/flask_api.py'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
                sh 'pydoc3 -w /var/lib/jenkins/workspace/jfile-100D-PrimeTools-API/products/024.primetools.web.api/'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
            sh 'sudo supervisorctl restart prime-tools'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
